export const CAFE_INFO = {
  name: "Café DOA",
  city: "Bad Nauheim",
  street: "Hauptstraße 11",
  postalCode: "61231",
  postalCity: "61231 Bad Nauheim",
  mapsUrl: "https://maps.google.com/?q=Hauptstra%C3%9Fe+11,+61231+Bad+Nauheim",
  phoneDisplay: "06032 / 78 43 278",
  phoneHref: "+4960327843278",
  instagramHandle: "@cafe.doa",
  instagramUrl: "https://www.instagram.com/cafe.doa/",
  openingHours: "Täglich 9:30 – 19:00 Uhr",
  kitchenHours: "Küche täglich bis 18:00 Uhr",
  siteUrl: "https://cafe-doa.de",
  reservationNote: "Reservierungsanfragen werden von uns telefonisch oder per E-Mail bestätigt.",
} as const;
